language: csharp
solution: "Planificador.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" Planificador.sln
script:
- xbuild Planificador.sln
- mono ./packages/xunit.runner.console*/tools/xunit.console.exe ./PlanificadorTests/bin/Debug/FibonacciTests.dll.dll