language: csharp
solution: Planificador.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Planificador.sln
after_script:
  - nunit-console PlanificadorTest/bin/Release/PlanificadorTest.dll