language: csharp
solution: Planificador.sln
install:
  - nuget restore Planificador.sln
  - nuget install NUnit -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Planificador.sln
  - mono ./NUnit.3.6.1/tools/nunit-console.exe ./PlanificadorTests/bin/Release/Planificador.Tests.dll
