
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Planificador.Models
{
    using System.Collections.Generic;
    
public partial class Alumno
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Alumno()
    {

        this.Cursada = new HashSet<Cursada>();

        this.PlanDeEstudio = new HashSet<PlanDeEstudio>();

    }


    public int Id { get; set; }

    public string Dni { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cursada> Cursada { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PlanDeEstudio> PlanDeEstudio { get; set; }

    public virtual Libreta Libreta { get; set; }

}

}
