//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrerasPorUsuario
    {
        public int IdCarreraPorUsuario { get; set; }
        public int IdUsuario { get; set; }
        public int IdCarrera { get; set; }
        public decimal Promedio { get; set; }
        public decimal PorcentajeCompletitud { get; set; }
    
        public virtual Alumno Usuario { get; set; }
        public virtual Carrera Carrera { get; set; }
    }
}
