
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Planificador.Models
{
    using System.Collections.Generic;
    
public partial class Correlativa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Correlativa()
    {

        this.MateriaCorrelativa = new HashSet<Materia>();

    }


    public string IdPlanEstudio { get; set; }

    public string IdMateria { get; set; }



    public virtual PlanDeEstudio PlanDeEstudios { get; set; }

    public virtual Materia Materia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Materia> MateriaCorrelativa { get; set; }

}

}
