//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativaPorMateria
    {
        public int IdCorrelativaPorMateria { get; set; }
        public int IdMateriaOrigen { get; set; }
        public int IdMateriaDestino { get; set; }
    
        public virtual MateriasPorCarrera MateriaOrigen { get; set; }
        public virtual MateriasPorCarrera MateriaDestino { get; set; }
    }
}
