//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativaPorMateria
    {
        public int IdCorrelativaPorMateria { get; set; }
        public int IdMateriaOrigen { get; set; }
        public int IdMateriaDestino { get; set; }
    
        public virtual MateriasPorCarrera MateriaOrigen { get; set; }
        public virtual MateriasPorCarrera MateriaDestino { get; set; }
    }
}
