
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Planificador.Models
{
    using System.Collections.Generic;
    
public partial class Cursada
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cursada()
    {

        this.Alumno = new HashSet<Alumno>();

        this.Materia = new HashSet<Materia>();

    }


    public string Comision { get; set; }

    public string Semestre { get; set; }

    public string Horarios { get; set; }

    public int ProfesorId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Alumno> Alumno { get; set; }

    public virtual Docente Profesor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Materia> Materia { get; set; }

}

}
