//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriasPorCarrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MateriasPorCarrera()
        {
            this.CorrelativaPorMateria = new HashSet<CorrelativaPorMateria>();
            this.CorrelativaPorMateria1 = new HashSet<CorrelativaPorMateria>();
        }
    
        public int IdMateriaPorCarrera { get; set; }
        public int IdMateria { get; set; }
        public int IdCarrera { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelativaPorMateria> CorrelativaPorMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelativaPorMateria> CorrelativaPorMateria1 { get; set; }
    }
}
