//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriasPorUsuario
    {
        public int IdMateriaPorUsuario { get; set; }
        public int IdUsuario { get; set; }
        public int IdMateria { get; set; }
        public bool EstaAprobada { get; set; }
        public short Nota { get; set; }
    
        public virtual Alumno Usuario { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
