//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planificador.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Materia> MateriaSet { get; set; }
        public virtual DbSet<Carrera> CarreraSet { get; set; }
        public virtual DbSet<MateriasPorCarrera> MateriasPorCarreraSet { get; set; }
        public virtual DbSet<CarrerasPorUsuario> CarrerasPorUsuarioSet { get; set; }
        public virtual DbSet<MateriasPorUsuario> MateriasPorUsuarioSet { get; set; }
        public virtual DbSet<CorrelativaPorMateria> CorrelativaPorMateriaSet { get; set; }
    }
}
