
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Planificador.Models
{
    using System.Collections.Generic;
    
public partial class PlanDeEstudio
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PlanDeEstudio()
    {

        this.Correlativas = new HashSet<Correlativa>();

        this.Materia = new HashSet<Materia>();

        this.Alumno = new HashSet<Alumno>();

    }


    public int Id { get; set; }

    public int CodigoCarrera { get; set; }

    public string FechaBaja { get; set; }



    public virtual Carrera Carrera { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Correlativa> Correlativas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Materia> Materia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Alumno> Alumno { get; set; }

}

}
